version: '3.8'
services:
  frontend:
    build: frontend
    env_file:
      - frontend/.env
    ports:
      - 3000:3000
  backend:
    build: backend
    env_file:
      - backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=socialhabits
